### ISSUE TITLE
thymeleaf에서 a태그를 이용해 spring security의 logout을 호출할 때 POST method로 보내야 하는 이슈

### ISSUE THREAD

**Issue by junghun95** [DDEiG/blog#11]
html header 페이지에서 로그아웃을 하고 싶어서

`<a th:href="@{/logout}" th:text="#{header.logout}" sec:authorize="isAuthenticated()" >로그아웃</a>`

이렇게  작성했을 때,

whitelabel페이지가 뜨는 상황.

security 공식문서에서는 security의 기본 logout을 사용할 경우, 따로 requestMatcher설정은 필요없고

get, post 둘다 지원하지만 post 를 쓰는게 좋다고 설명되어있음.

a 태그에서 post method를 호출하는 방법 찾아보기 (아니면 그냥 로그아웃 버튼을 만들어도 될듯 -> 버튼으로 하면 동작함)

시큐리티 공식 문서 - https://docs.spring.io/spring-security/reference/servlet/authentication/logout.html#permit-logout-endpoints

**Comment by taekhyeonn** [comment]
CSRF token이 없어 생긴 오류
해당 전달값 추가 하여 해결
